version: '3.8'

services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: swe573_database
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend
    dns:
      - 8.8.8.8  # Google DNS

  web:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    environment:
      DATABASE_URL: "postgresql://postgres:password@db/swe573_database"
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - backend
    dns:
      - 8.8.8.8  # Google DNS

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      - backend
    dns:
      - 8.8.8.8  # Google DNS

networks:
  backend:

volumes:
  postgres_data:
