# Generated by Django 4.2.11 on 2024-05-20 02:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('swe573app', '0004_communitytemplate_post_alter_community_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='following', to=settings.AUTH_USER_MODEL),
        ),
    ]
