# Generated by Django 4.2.11 on 2024-05-20 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swe573app', '0006_community_description_community_moderators'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
