# Generated by Django 4.2.11 on 2024-05-20 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swe573app', '0008_profile'),
    ]

    operations = [
    ]
