# Generated by Django 4.2.11 on 2024-05-20 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swe573app', '0010_auto_20240520_0441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='template',
        ),
        migrations.AddField(
            model_name='community',
            name='templates',
            field=models.ManyToManyField(blank=True, to='swe573app.communitytemplate'),
        ),
    ]
