# Generated by Django 4.2.11 on 2024-05-20 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swe573app', '0013_post_author_post_data_post_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('fields', models.JSONField()),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swe573app.community')),
            ],
        ),
    ]
