# Generated by Django 4.2.11 on 2024-05-20 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swe573app', '0014_template'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='templates',
        ),
        migrations.AlterField(
            model_name='template',
            name='community',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='swe573app.community'),
        ),
    ]
