# Generated by Django 4.2.11 on 2024-05-20 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swe573app', '0015_remove_community_templates_alter_template_community'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitytemplate',
            name='community',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='community_templates', to='swe573app.community'),
        ),
    ]
