# Generated by Django 4.2.11 on 2024-05-20 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swe573app', '0016_communitytemplate_community'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitytemplate',
            name='community',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='community_templates', to='swe573app.community'),
        ),
    ]
